routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@getIndex');

Route::get('about', "PagesController@getAbout");

Route::resource('suppliers', 'SupplierController');

Route::resource('customers','CustomerController');

Route::resource('employees','EmployeeController');

Route::resource('items', 'ItemController');

Route::resource('receivings','ReceivingController');

Route::resource('sales','SaleController');

//Route::get('/', function () {
  //  return view('welcome');
//});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    //
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Customer;
use App\Http\Resources\Customer as CustomerResource;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $customers = Customer::all();
        return view('customers.index')->withCustomers($customers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $customer = new Customer;

        $customer->name = $request->name;
        $customer->email = $request->email;
        $customer->phone_number = $request->phone_number;
        $customer->address = $request->address;
        $customer->comment = $request->comment;
        $customer->company_name = $request->company_name;
        $customer->account = $request->account;

        $customer->save();

        return view('customers.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return new CustomerResource(Customer::find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customers/index.blade.php
@extends('main')


@section('content')

<div class="col-md-12">
	    <div class="box">
		<div class="box-header">

	      <div class="col-md-3">
			<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal2">Add Customers</button><br><hr>

		  </div> 
		  

			<div class="modal fade" id="myModal2" role="dialog">
				<div class="modal-dialog">

				  <!-- Modal content-->
				  <div class="modal-content">

				    <div class="modal-header">
				      <button type="button" class="close" data-dismiss="modal">&times;</button>
				      <h4 class="modal-title">Create New Customer</h4>
				    </div>
				    
				    <div class="modal-body">
				    {!! Form::open(array('route' => 'customers.store', 'class'=>'form-horizontal form-horizontal-option', 'files' => true)) !!}
				  	
				  	 {{ Form::label('name','Name:')}}
           			 {{ Form::text('name', null, array('class'=>'form-control'))}}

           			 {{ Form::label('email', 'Email:')}}
           			 {{ Form::text('email',null, array('class'=>'form-control'))}}

           			 {{ Form::label('phone_number', 'Phone Number:')}}
           			 {{ Form::text('phone_number', null, array('class'=>'form-control'))}}

           			 {{ Form::label('address','Address:')}}
           			 {{ Form::text('address', null, array('class'=>'form-control'))}}

           			 {{ Form::label('comment','Comment:')}}
           			 {{ Form::text('comment', null,array('class'=>'form-control'))}}

           			 {{ Form::label('company_name','Company Name:')}}
           			 {{ Form::text('company_name', null, array('class'=>'form-control'))}}

           			 {{ Form::label('account', 'Account:')}}
           			 {{ Form::text('account',null, array('class'=>'form-control'))}}

           			 {{ Form::submit('Submit', array('class' => 'btn btn-success btn-md btn-block', 'style' => 'margin-top: 20px;')) }}


				    {!! Form::close() !!}
				     
					  </div>

					 
					 
					  </div> 
				</div>
				<!--/.modal-dialog-->
			</div>	
		</div>
		 <!-- /.box-header -->

         

	    <div class="box-body">
	 
	    		
	      <table id="example2" class="table table-bordered table-hover">
	        <thead>
	        <tr>
	          <th>Customer ID</th>
	          <th>Name</th>
	          <th>Email</th>
	          <th>Phone Number</th>
	          <th>Image</th>
	          <th>Action</th>
	        </tr> 
	        </thead>
	        <tbody> 
	       		@foreach($customers as $customer)
	       		<tr>
	       			<th>{{$customer->id}}</th>
	       			<th>{{$customer->name}}</th>
	       			<th>{{$customer->email}}</th>
	       			<th>{{$customer->phone_number}}</th>
	       			<th></th>
	       			<td><a href="{{ route('customers.show', $customer->id) }}" class="btn btn-default btn-sm">View</a><a href="#" class="btn btn-primary btn-sm">Edit</a><a href="" class="btn btn-danger btn-sm">Delete</a></td>
	       		</tr>

	       		@endforeach

	        
	        </tbody>
	        <tfoot>
	        <tr>
	          <th>Customer ID</th>
	          <th>Name</th>
	          <th>Email</th>
	          <th>Phone Number</th>
	          <th>Image</th>
	          <th>Action</th>
	        </tr> 
	        </tfoot>
	      </table>
	    </div>
	    <!-- /.box-body -->

	    <div class="box-footer clearfix">
	      <ul class="pagination pagination-sm no-margin pull-right">
	        <li><a href="#">&laquo;</a></li>
	        <li><a href="#">1</a></li>
	        <li><a href="#">2</a></li>
	        <li><a href="#">3</a></li>
	        <li><a href="#">&raquo;</a></li>
	      </ul>
	    </div>
  </div>	  
  <!-- /.box -->
</div>
</div>
@endsection